In [1]:
import numpy as np

In [2]:
array_1d = np.array([1,2,3])  
array_2d = np.array([(1.5,2,3), (4,5,6)], dtype = float)  
array_3d = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

np.zeros((3,4))                  #Create an array of zeros
np.ones((2,3,4),dtype=np.int16)  #Create an array of ones  
np.arange(10,25,5)               #Create an array of evenly spaced values (step value)  
np.linspace(0,2,9)               #Create an array of evenly spaced values (number of samples)  
np.full((2,2),7)                 #Create a constant array  
np.eye(2)                        #Create a 2X2 identity matrix  
np.random.random((2,2))          #Create an array with random values  
np.empty((3,2))                  #Create an empty array



array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

## I/O
Data opslaan en laden

In [6]:
a = np.zeros((2, 8))
             
np.save('my_array' , a)  
# np.savez('my_array', a, b)  
b = np.load('my_array.npy')
             
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
#np.loadtxt("myfile.txt")  
#np.genfromtxt("my_file.csv", delimiter=',')  
#np.savetxt("myarray.txt", a, delimiter=" ")

/home/stijn/PythonProjects/hello-python


## Array opties

In [8]:
a = np.zeros((2,8))

a.shape  #Array dimensions  
len(a)   #Length of array
b.ndim   #Number of array dimensions
a.size   #Number of array elements  
a.dtype  #Data type of array elements 
a.dtype.name  #Name of data type  
a.astype(int) #Convert an array to a different type

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

## Data types

In [ ]:
np.int64 #Signed 64-bit integer types  
np.float32 #Standard double-precision floating point  
np.complex#Complex numbers represented by 128 floats 
np.bool#Boolean type storing TRUE and FALSE values  
np.object#Python object type 
np.string_#Fixed-length string type  
np.unicode_#Fixed-length unicode type

## Essential operations

In [18]:
a = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b = np.array([(0.1, 1, 0.1), (1, 0.1, 1)], dtype = float)

print((a - b) == np.subtract(a,b)) #Subtraction  
print((a + b) == np.add(b, a)) #Addition
print((a / b) == np.divide(a,b)) #Division
print((a * b) == np.multiply(a,b)) #Multiplication

np.exp(a)  #Exponentiation
np.sqrt(a) #Square root  
np.sin(a)  #Element-wise sine
np.cos(a)  #Element-wise cosine  
np.log(a)  #Element-wise natural logarithm
# a.dot(b)   #Dot product

a == b #Element-wise comparison
a < 2 #Element-wise comparison  
print(np.array_equal(a, b)) #Array-wise comparison

[[ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]]
False


In [24]:
a.sum() #Array-wise sum  
a.min() #Array-wise minimum value 
a.max(axis=0) #Maximum value of an array row 
a.cumsum(axis=1) #Cumulative sum of the elements  
a.mean() #Mean  
np.median(a) #Median  
np.corrcoef(a) #Correlation coefficient  
np.std(a) #Standard deviation


1.5920810978785667

In [25]:
h = a.view() #Create a view of the array with the same data  
a_copy = np.copy(a) #Create a copy of the array 
a_deepcopy = a.copy() #Create a deep copy of the array

## Subsetting, Slicing, Indexing

In [28]:
a[1] #Select the element at the 2nd index  
b[1,2] #Select the element at row 1 column 2 (equivalent to b[1][2]) 

   
a[0:2] #Select items at index 0 and 1
b[0:2,1] #Select items at rows 0 and 1 in column 1  
b[:1] #Select all items at row 0 (equivalent to b[0:1, :])  
b[1,...] #Same as [1,:,:]

# Selecting a row:
a[...,0]

# Selecting a column:
a[0,...]

a[ : :-1] #Reversed array a array([3, 2, 1])

a[a<2] #Select elements from a less than 2
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)  
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns 

array([[1. , 0.1, 1. , 1. ],
       [0.1, 1. , 0.1, 0.1],
       [1. , 0.1, 1. , 1. ],
       [0.1, 1. , 0.1, 0.1]])

## Array Manipulation

In [32]:
# Transposing arrays
print(np.transpose(a) == a.T)

# Changing array shapes:
print(a.ravel()) #Flatten the array  
print(a.reshape(3,-2))#Reshape, but don’t change data

[[ True  True]
 [ True  True]
 [ True  True]]
[1.5 2.  3.  4.  5.  6. ]
[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]


In [14]:
# Adding or Removing Elements
a = np.array([(1,2,3), (4,5,6)], dtype = float)
# g = a.ravel()
b = np.zeros((2,3))

# print(a.resize((2,6))) #Return a new array with shape (2,6)  
# print(np.append(a,b)) #flatten and append
# print(np.insert(a, 6, 11)) #Insert items in an array at location
print(np.delete(a,[1])) #Delete items from an array

[1. 3. 4. 5. 6.]


In [48]:
a = np.arange(0,24,1)
a = a.reshape(3,-1)
print(a)
# print(a.shape, a.ndim, a.size)

# print(np.concatenate((a,b),axis=0)) #Concatenate arrays 

# Vertical and horizontal stacking
# print(np.vstack((a,b))) #Stack arrays vertically (row-wise) 
# print(np.r_[a,b]) #Stack arrays vertically (row-wise)  

# print(np.hstack((a,b))) #Stack arrays horizontally (column-wise)  
# print(np.column_stack((a,b))) #Stack arrays horizontally (column-wise)  
# print(np.c_[a,b]) #Stack arrays horizontally (column-wise)  
 
# Splitting
# print(np.hsplit(a,2)) #Split the array horizontally at the 3rd index
# print(np.vsplit(a,2)) #Split the array vertically at the 2nd index 

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


10
20
30
40
50
60
70
